rules:
  no_dead_ends:
    report: "error"
    allowed_names:
      - CUSTOM_STOP


ignore:
  - "**/node_modules/**"
  - "**/package.json"
  - "**/package-lock.json"
  - "**/yarn.lock"
  - "**/dist/**"
  - "**/.releaserc.json"

include:
  - "**/*.json"
